USE [vizal]
GO

/****** Object:  Table [dbo].[EMPLOYEE_INFORMATIONSS]    Script Date: 02-08-2023 19:13:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPLOYEE_INFORMATIONSS](
	[EMPLOYEE_ID] [int] IDENTITY(1,1) NOT NULL,
	[Full_NAME] [varchar](50) NULL,
	[DATE_OF_BIRTH] [varchar](10) NULL,
	[GENDER] [varchar](9) NULL,
	[ADDRESS] [varchar](max) NULL,
	[CONTACT_NUMBER] [bigint] NULL,
	[EMAIL_ADDRESS] [varchar](50) NULL,
	[DEPARTMENT] [varchar](50) NULL,
	[PROGRAMMING] [bit] NULL,
	[COMMUNICATION] [bit] NULL,
	[LEADERSHIP] [bit] NULL,
	[PROBLEM_SOLVING] [bit] NULL,
	[CREATED_TIME] [datetime] NULL,
	[Updated_time] [datetime] NULL,
	[IS_DELETED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[EMPLOYEE_INFORMATIONSS] ADD  DEFAULT ((0)) FOR [IS_DELETED]
GO


